app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
  path: /login
  defaults: { _controller: AppBundle:Security:login }

logout:
    path: /logout

user_registration:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }

catalog:
    path: /catalog
    defaults: { _controller: AppBundle:Catalog:show }