# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /logout

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGE_PRODUCT, ROLE_MANAGE_CATEGORY, ROLE_MANAGE_USER, ROLE_BROWSE_CATALOG, ROLE_ALLOWED_TO_SWITCH]
        ROLE_MOD: [ROLE_MANAGE_PRODUCT, ROLE_MANAGE_CATEGORY, ROLE_BROWSE_CATALOG]
        ROLE_USER: [ROLE_BROWSE_CATALOG]


    access_control:
        # require ROLE_ADMIN for /admin*
        #- { path: /, roles: ROLE_USER }
        - { path: ^/admin/user, roles: ROLE_MANAGE_USER }
        - { path: ^/admin/product, roles: ROLE_MANAGE_PRODUCT }
        - { path: ^/catalog, roles: ROLE_BROWSE_CATALOG }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
