# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    password_recovery:
        class: AppBundle\Services\PasswordRecoveryService
        autowire: true
#        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
    category_service:
        class: AppBundle\Services\CategoryService
        autowire: true
    products_service:
        class: AppBundle\Services\ProductsService
        autowire: true
    data_processor:
        class: AppBundle\Services\DataProcessor
        autowire: true
    form_utils:
        class: AppBundle\Services\FormUtilsService
#        arguments: ["@security.password_encoder"]
# , "plain_value", "%parameter_name%"
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }